wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1671660297.142941
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 64
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 7
client_num_per_round:
  desc: null
  value: 5
client_optimizer:
  desc: null
  value: adam
comm_round:
  desc: null
  value: 23
config_id:
  desc: null
  value: 0
data_dir:
  desc: null
  value: ./data/cifar10
data_parallel:
  desc: null
  value: 0
dataset:
  desc: null
  value: cifar10
epochs:
  desc: null
  value: 10
frequency_of_test_acc_report:
  desc: null
  value: 1
frequency_of_the_test:
  desc: null
  value: 1
frequency_of_train_acc_report:
  desc: null
  value: 1
gpu:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.5061576888752303
model:
  desc: null
  value: resnet18
noise_rate:
  desc: null
  value: 0.0
partition_alpha:
  desc: null
  value: 1.160126459986672
partition_method:
  desc: null
  value: non-iid
run_name:
  desc: null
  value: FedAVG-r-v2
wd:
  desc: null
  value: 0.0008471801418819973
