wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1680082798.52602
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.6
      5: 0.13.10
      8:
      - 5
agg_type:
  desc: null
  value: stack
batch_size:
  desc: null
  value: 64
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 11
client_num_per_round:
  desc: null
  value: 5
client_optimizer:
  desc: null
  value: adam
config_id:
  desc: null
  value: 0.0
cut_layer:
  desc: null
  value: 9.0
data_dir:
  desc: null
  value: ./data/cifar10
data_parallel:
  desc: null
  value: 0
dataset_id:
  desc: null
  value: 4134
dataset_index_id:
  desc: null
  value: 0
desc:
  desc: null
  value: All varient. nLn fixed. Aggregation check. 1 datasets (200 runs). Seed is
    fixed.
epochs:
  desc: null
  value: 15
frequency_of_test_acc_report:
  desc: null
  value: 1
frequency_of_the_test:
  desc: null
  value: 1
frequency_of_train_acc_report:
  desc: null
  value: 1
gpu:
  desc: null
  value: 0
ln_upscale:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.01
model:
  desc: null
  value: resnet18
noise_rate:
  desc: null
  value: 0.0
num_ln:
  desc: null
  value: 10
partition_alpha:
  desc: null
  value: 15.403596595019248
random_seed:
  desc: null
  value: 0
run_name:
  desc: null
  value: Split_Learning
wd:
  desc: null
  value: 0.01
